apiVersion: v1
kind: Service
metadata:
  labels:
    app: spring-deploy
  name: spring-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-deploy
  type: NodePort
status:
  loadBalancer: {}
