version: '3.7'
services:
  jenkins:
   # build: .
    image: docker.io/jenkins/jenkins:latest 
    privileged: true
    restart: always
    user: root
    ports:
      - 8080:8080
    container_name: jenkins-lts
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
